In [75]:
#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline-2532032022/refs/heads/main/data/raw/F_clientes.csv"

clientes = pd.read_csv(url)
clientes.head()

  id_cliente             cliente                  correo  telefono
0     CL1000     Paola Mendoza 0  cliente061@empresa.com  73372703
1     CL1001    Elena Ramírez 1   cliente186@outlook.com  75447071
2     CL1002  Valeria Martínez 2   cliente25@outlook.com  76605966
3     CL1003    Daniela Rivera 3    cliente317@correo.sv  73134898
4     CL1004     Elena Morales 4    cliente426@correo.sv  78399637

In [76]:
#EXPLORACION DE DATOS

#clientes.shape #filas, columnas
#clientes.columns
#clientes.info()
clientes.isnull().sum() #cuenta los valores nulos

id_cliente    0
cliente       0
correo        7
telefono      4
dtype: int64

In [77]:
#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(clientes):
    clientes.columns = (
        clientes.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return clientes

# Limpia solamente textos
def limpiar_texto(clientes):
    for col in clientes.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        clientes[col] = clientes[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        clientes[col] = clientes[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return clientes

#APLICA LIMPIEZA GENERAL
clientes = normalizar_columnas(clientes)
clientes = limpiar_texto(clientes)
clientes=clientes.drop_duplicates() #Elimina duplicados

In [78]:
#LIMPIEZA DE DATOS ESPECIFICOS

#Cliente
import unicodedata

clientes["cliente"] = (
    clientes["cliente"]
    .astype(str)
    .apply(lambda x: unicodedata.normalize('NFKD', x)
           .encode('ascii', 'ignore')
           .decode('utf-8'))
    .str.title()
)
clientes["cliente"] = clientes["cliente"].replace(["", " ", "NULL", "null", "None", "nan"],pd.NA)

#Correo
clientes["correo"] = clientes["correo"].astype("string").str.lower().str.strip()
clientes["correo"] = clientes["correo"].replace(
    ["", " ", "NULL", "null", "None", "nan"], pd.NA
)

#Telefono
clientes["telefono"] = clientes["telefono"].replace(["", " ", "NULL", "null", "None", "nan"],pd.NA)

In [79]:
#SEPARAR DATOS INVALIDOS Y RECHAZADOS

clientes_validos=clientes[
    clientes['cliente'].notna()&
    clientes['correo'].notna()&
    clientes['telefono'].notna()
].copy()


clientes_rechazados=clientes[
    clientes["cliente"].isna() |
    clientes['correo'].isna() |
    clientes['telefono'].isna()
].copy()

In [80]:
#MOTIVO DE RECHAZO

def motivo(row):
  motivos=[]

  if pd.isna(row['cliente']):
    motivos.append("cliente_vacio")

  if pd.isna(row['correo']):
    motivos.append("correo_vacio")

  if pd.isna(row['telefono']):
    motivos.append("telefono_vacio")

  return ";".join(motivos)

clientes_rechazados["motivo_rechazo"] = clientes_rechazados.apply(motivo,axis=1)

In [81]:
#VERIFICAR SI HAY DATOS NULOS
print(clientes.isna().sum())

id_cliente    0
cliente       0
correo        7
telefono      4
dtype: int64

In [63]:
#EXPORTAR ARCHIVOS

clientes_validos.to_csv("clientes_curated.csv", index=False)

clientes_rechazados.to_csv("clientes_rejects.csv", index=False)

In [82]:
#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [83]:
engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [92]:
#CARGAR DATOS EN PostgreSQL

if clientes_validos.empty:
    print("⚠ No hay datos válidos")

if clientes_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    clientes_validos.to_sql('clientes_curated_parcial02', engine, if_exists='append', index=False)
    clientes_rechazados.to_sql('clientes_rejects_parcial02', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

Carga exitosa ✅

In [94]:
#VALIDAR LA CARGA
pd.read_sql(
    "SELECT * FROM clientes_curated_parcial02 LIMIT 10",
    engine
)

  id_cliente             cliente                  correo  telefono
0     cl1000     Paola Mendoza 0  cliente061@empresa.com  73372703
1     cl1001     Elena Ramirez 1  cliente186@outlook.com  75447071
2     cl1002  Valeria Martinez 2   cliente25@outlook.com  76605966
3     cl1003    Daniela Rivera 3    cliente317@correo.sv  73134898
4     cl1004     Elena Morales 4    cliente426@correo.sv  78399637
5     cl1005       Ana Mendoza 5     cliente555gmail.com  78847864
6     cl1007   Marta Hernandez 7  cliente735@empresa.com  72952127
7     cl1008      Diego Torres 8  cliente870@empresa.com  79305719
8     cl1009   Daniela Morales 9    cliente987@gmail.com  79050212
9     cl1011   Daniela Santos 11    cliente117@gmail.com  77253653

In [95]:
#VALIDAR LA CARGA
pd.read_sql(
    "SELECT * FROM clientes_rejects_parcial02 LIMIT 10",
    engine
)

,id_cliente,cliente,correo,telefono,motivo_rechazo
0,cl1006,Andres Lopez 6,cliente645@outlook.com,None,telefono_vacio
1,cl1010,Fernando Gomez 10,None,76885202,correo_vacio
2,cl1012,Carmen Rivas 12,cliente1272@outlook.com,None,telefono_vacio
3,cl1027,Elena Ramirez 27,None,73992809,correo_vacio
4,cl1034,Marta Cruz 34,cliente3454@gmail.com,None,telefono_vacio
5,cl1077,Diego Morales 77,None,75356137,correo_vacio
6,cl1084,Andres Romero 84,None,None,correo_vacio;telefono_vacio
7,cl1094,Paola Guerrero 94,None,73486962,correo_vacio
8,cl1100,Carmen Torres 100,None,79293388-,correo_vacio
9,cl1105,Jose Gomez 105,None,74726461,correo_vacio