In [15]:
#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline-2532032022/refs/heads/main/data/raw/F_envios.csv"

envios = pd.read_csv(url)
envios.head()

,id_envio,id_pedido,direccion,fecha_envio,estado_envio
0,ENV8000,PED7100,"Boulevard Constitución, San Salvador",2024-06-02,en ruta
1,ENV8001,PED7222,"Calle El Mirador, La Libertad",2024-05-07,entregado
2,ENV8002,PED7191,"Calle El Mirador, Sonsonate",2024-05-30,devuelto
3,ENV8003,PED7186,"Av. Roosevelt, San Miguel",2024-07-03,en ruta
4,ENV8004,PED7043,"Calle Principal, San Salvador",2024-01-09,preparando

In [24]:
#EXPLORACION DE DATOS

#envios.shape #filas, columnas
#envios.columns
#envios.info()
envios.isnull().sum() #cuenta los valores nulos

id_envio         0
id_pedido        8
direccion        0
fecha_envio     15
estado_envio     0
dtype: int64

In [17]:
#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(envios):
    envios.columns = (
        envios.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return envios

# Limpia solamente textos
def limpiar_texto(envios):
    for col in envios.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        envios[col] = envios[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        envios[col] = envios[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return envios

#APLICA LIMPIEZA GENERAL
envios = normalizar_columnas(envios)
envios = limpiar_texto(envios)
envios= envios.drop_duplicates() #Elimina duplicados

In [18]:
# Ver correos duplicados y cuántas veces se repiten
envios["estado_envio"].value_counts()[envios["estado_envio"].value_counts() > 1]

estado_envio
entregado     65
devuelto      55
en ruta       46
preparando    44
Name: count, dtype: int64

In [19]:
#LIMPIEZA DE DATOS ESPECIFICOS

#id_pedido
envios["id_pedido"] = envios["id_pedido"].astype("string").str.lower().str.strip()
envios["id_pedido"] = envios["id_pedido"].replace(["", " ", "NULL", "null", "None", "nan"], pd.NA)

#direccion
envios["direccion"] = (envios["direccion"].astype(str).str.strip().str.title())

#fecha_envio
envios["fecha_envio"] = pd.to_datetime(
    envios["fecha_envio"],
    errors="coerce",
    format="mixed"
)

#estado_envio
envios["estado_envio"] = (
    envios["estado_envio"].astype(str).str.strip().str.lower().map({
        "entregado":"Entregado",
        "devuelto":"Devuelto",
        "en ruta":"En Ruta",
        "preparando":"Preparando"
        })
)

In [20]:
envios

,id_envio,id_pedido,direccion,fecha_envio,estado_envio
0,env8000,ped7100,"Boulevard Constitución, San Salvador",2024-06-02,En Ruta
1,env8001,ped7222,"Calle El Mirador, La Libertad",2024-05-07,Entregado
2,env8002,ped7191,"Calle El Mirador, Sonsonate",2024-05-30,Devuelto
3,env8003,ped7186,"Av. Roosevelt, San Miguel",2024-07-03,En Ruta
4,env8004,ped7043,"Calle Principal, San Salvador",2024-01-09,Preparando
...,...,...,...,...,...
205,env8205,ped7173,"Boulevard Constitución, San Salvador",2024-08-30,Entregado
206,env8206,ped7192,"Av. Roosevelt, La Libertad",2025-05-06,Preparando
207,env8207,ped7019,"Calle Principal, San Miguel",2025-01-27,Entregado
208,env8208,ped7157,"Col. Escalón, Usulután",2024-12-21,Preparando
209,env8209,ped7195,"Av. Roosevelt, Sonsonate",2024-07-09,En Ruta

In [29]:
#SEPARAR DATOS INVALIDOS Y RECHAZADOS

envios_validos=envios[
    envios['id_pedido'].notna()&
    envios['direccion'].notna()&
    envios['fecha_envio'].notna()&
    envios['estado_envio'].notna()
].copy()


envios_rechazados=envios[
    envios['id_pedido'].isna()|
    envios['direccion'].isna()|
    envios['fecha_envio'].isna()|
    envios['estado_envio'].isna()
].copy()

In [30]:
#MOTIVO DE RECHAZO

def motivo(row):
  motivos=[]

  if pd.isna(row['id_pedido']):
    motivos.append("id_pedido_vacio")

  if pd.isna(row['direccion']):
    motivos.append("direccion_vacio")

  if pd.isna(row['fecha_envio']):
    motivos.append("fecha_envio_vacio")

  if pd.isna(row['estado_envio']):
    motivos.append("estado_envio_vacio")

  return ";".join(motivos)

envios_rechazados["motivo_rechazo"] = envios_rechazados.apply(motivo,axis=1)

In [31]:
#VERIFICAR SI HAY DATOS NULOS
print(envios.isna().sum())

id_envio         0
id_pedido        8
direccion        0
fecha_envio     15
estado_envio     0
dtype: int64

In [33]:
#EXPORTAR ARCHIVOS

envios_validos.to_csv("envios_curated.csv", index=False)

envios_rechazados.to_csv("envios_rejects.csv", index=False)

In [36]:
#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 32.6 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [37]:
engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [38]:
#CARGAR DATOS EN PostgreSQL

if envios_validos.empty:
    print("⚠ No hay datos válidos")

if envios_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    envios_validos.to_sql('envios_curated_parcial02', engine, if_exists='append', index=False)
    envios_rechazados.to_sql('envios_rejects_parcial02', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

Carga exitosa ✅

In [39]:
#VALIDAR LA CARGA
pd.read_sql(
    "SELECT * FROM envios_curated_parcial02 LIMIT 10",
    engine
)

,id_envio,id_pedido,direccion,fecha_envio,estado_envio
0,env8000,ped7100,"Boulevard Constitución, San Salvador",2024-06-02,En Ruta
1,env8001,ped7222,"Calle El Mirador, La Libertad",2024-05-07,Entregado
2,env8002,ped7191,"Calle El Mirador, Sonsonate",2024-05-30,Devuelto
3,env8003,ped7186,"Av. Roosevelt, San Miguel",2024-07-03,En Ruta
4,env8004,ped7043,"Calle Principal, San Salvador",2024-01-09,Preparando
5,env8005,ped7008,"Pje. Las Flores, Sonsonate",2024-03-03,Devuelto
6,env8006,ped7169,"Av. Roosevelt, San Salvador",2024-04-04,Devuelto
7,env8007,ped7153,"Calle Principal, Usulután",2024-09-07,Devuelto
8,env8008,ped7207,"Calle Principal, San Salvador",2025-04-23,En Ruta
9,env8009,ped7103,"Boulevard Constitución, Santa Ana",2025-05-07,Entregado

In [40]:
#VALIDAR LA CARGA
pd.read_sql(
    "SELECT * FROM envios_rejects_parcial02 LIMIT 10",
    engine
)

,id_envio,id_pedido,direccion,fecha_envio,estado_envio,motivo_rechazo
0,env8017,ped7073,"Calle El Mirador, Santa Ana",NaT,En Ruta,fecha_envio_vacio
1,env8045,ped7205,"Col. Escalón, Sonsonate",NaT,Entregado,fecha_envio_vacio
2,env8056,None,"Boulevard Constitución, Sonsonate",2024-12-22,Devuelto,id_pedido_vacio
3,env8058,ped7183,"Pje. Las Flores, San Salvador",NaT,En Ruta,fecha_envio_vacio
4,env8061,ped7205,"Av. Roosevelt, San Salvador",NaT,En Ruta,fecha_envio_vacio
5,env8067,ped7089,"Pje. Las Flores, Santa Ana",NaT,En Ruta,fecha_envio_vacio
6,env8074,ped7165,"Col. Escalón, La Libertad",NaT,Preparando,fecha_envio_vacio
7,env8083,ped7176,"Col. Escalón, San Salvador",NaT,Preparando,fecha_envio_vacio
8,env8084,ped7131,"Calle El Mirador, Santa Ana",NaT,En Ruta,fecha_envio_vacio
9,env8104,ped7144,"Calle El Mirador, San Miguel",NaT,En Ruta,fecha_envio_vacio