In [14]:
#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd
import numpy as np
import re

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline-2532032022/refs/heads/main/data/raw/F_pedidos.csv"

pedidos = pd.read_csv(url)
pedidos.head()

  id_pedido id_cliente fecha_pedido    monto     estado
0   PED7000     CL1138   2024-11-28  1984.03   enviado
1   PED7001        NaN   2025-01-31  2395.24  cancelado
2   PED7002     CL1067   2024-07-13   433.46  cancelado
3   PED7003     CL1097   2025-05-02   352.01  cancelado
4   PED7004     CL1068   2024-12-20  1182.84    enviado

In [15]:
#EXPLORACION DE DATOS

#pedidos.shape #filas, columnas
#pedidos.columns
#pedidos.info()
pedidos.isnull().sum() #cuenta los valores nulos

id_pedido       0
id_cliente      6
fecha_pedido    5
monto           6
estado          0
dtype: int64

In [16]:
#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(pedidos):
    pedidos.columns = (
        pedidos.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return pedidos

# Limpia solamente textos
def limpiar_texto(pedidos):
    for col in pedidos.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        pedidos[col] = pedidos[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        pedidos[col] = pedidos[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return pedidos

#APLICA LIMPIEZA GENERAL
pedidos = normalizar_columnas(pedidos)
pedidos = limpiar_texto(pedidos)
pedidos= pedidos.drop_duplicates() #Elimina duplicados

In [17]:
# Ver estados duplicados y cuántas veces se repiten
pedidos["estado"].value_counts()[pedidos["estado"].value_counts() > 1]

estado
cancelado      58
preparacion    48
enviado        46
pendiente      40
entregado      38
Name: count, dtype: int64

In [20]:
#LIMPIEZA DE DATOS ESPECIFICOS

#id_pedido
pedidos["id_cliente"] = pedidos["id_cliente"].astype("string").str.lower().str.strip()
pedidos["id_cliente"] = pedidos["id_cliente"].replace(["", " ", "NULL", "null", "None", "nan"], pd.NA)

#fecha_pedido
pedidos["fecha_pedido"] = pd.to_datetime(
    pedidos["fecha_pedido"],
    errors="coerce",
    format="mixed"
)

#monto
def limpiar_monto(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip().lower()

    # falsos nulos
    if x in ["", "-", "none", "nan", "null"]:
        return np.nan

    # eliminar símbolos (moneda, letras)
    x = re.sub(r"[^\d,.\-]", "", x)

    if "," in x and "." in x:
        # europeo → coma decimal
        if x.rfind(",") > x.rfind("."):
            x = x.replace(".", "").replace(",", ".")
        else:
            x = x.replace(",", "")

    elif x.count(",") > 1:
        # miles con comas
        x = x.replace(",", "")

    elif "," in x:
        # decimal con coma
        x = x.replace(",", ".")

    return x

col = pedidos["monto"].apply(limpiar_monto)
pedidos["monto"] = pd.to_numeric(col, errors="coerce")

#estado
pedidos["estado"] = (
    pedidos["estado"].astype(str).str.strip().str.lower().map({
        "cancelado":"Cancelado",
        "preparacion":"Preparacion",
        "enviado":"Enviado",
        "pendiente":"Pendiente",
        "entregado":"Entregado"
        })
)

In [21]:
pedidos

    id_pedido id_cliente fecha_pedido    monto       estado
0     ped7000     cl1138   2024-11-28  1984.03      Enviado
1     ped7001       <NA>   2025-01-31  2395.24    Cancelado
2     ped7002     cl1067   2024-07-13   433.46    Cancelado
3     ped7003     cl1097   2025-05-02   352.01    Cancelado
4     ped7004     cl1068   2024-12-20  1182.84      Enviado
..        ...        ...          ...      ...          ...
225   ped7225     cl1118   2024-11-11   459.90    Cancelado
226   ped7226     cl1040          NaT   697.55  Preparacion
227   ped7227     cl1001   2024-09-30    65.82  Preparacion
228   ped7228     cl1119   2025-01-14  1464.83    Pendiente
229   ped7229     cl1058   2024-10-14  2220.16  Preparacion

[230 rows x 5 columns]

In [24]:
#SEPARAR DATOS INVALIDOS Y RECHAZADOS

pedidos_validos=pedidos[
    pedidos['id_cliente'].notna()&
    pedidos['fecha_pedido'].notna()&
    pedidos['monto'].notna()&
    pedidos['estado'].notna()
].copy()


pedidos_rechazados=pedidos[
    pedidos['id_cliente'].isna()|
    pedidos['fecha_pedido'].isna()|
    pedidos['monto'].isna()|
    pedidos['estado'].isna()
].copy()

In [25]:
#MOTIVO DE RECHAZO

def motivo(row):
  motivos=[]

  if pd.isna(row['id_cliente']):
    motivos.append("id_cliente_vacio")

  if pd.isna(row['fecha_pedido']):
    motivos.append("fecha_pedido_vacio")

  if pd.isna(row['monto']):
    motivos.append("monto_vacio")

  if pd.isna(row['estado']):
    motivos.append("estado_vacio")

  return ";".join(motivos)

pedidos_rechazados["motivo_rechazo"] = pedidos_rechazados.apply(motivo,axis=1)

In [26]:
#VERIFICAR SI HAY DATOS NULOS
print(pedidos.isna().sum())

id_pedido       0
id_cliente      6
fecha_pedido    8
monto           6
estado          0
dtype: int64

In [27]:
#EXPORTAR ARCHIVOS

pedidos_validos.to_csv("pedidos_curated.csv", index=False)

pedidos_rechazados.to_csv("pedidos_rejects.csv", index=False)

In [28]:
#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 90.6 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [29]:
engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [30]:
#CARGAR DATOS EN PostgreSQL

if pedidos_validos.empty:
    print("⚠ No hay datos válidos")

if pedidos_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    pedidos_validos.to_sql('pedidos_curated_parcial02', engine, if_exists='append', index=False)
    pedidos_rechazados.to_sql('pedidos_rejects_parcial02', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

Carga exitosa ✅

In [31]:
#VALIDAR LA CARGA
pd.read_sql(
    "SELECT * FROM pedidos_curated_parcial02 LIMIT 10",
    engine
)

  id_pedido id_cliente fecha_pedido    monto       estado
0   ped7000     cl1138   2024-11-28  1984.03      Enviado
1   ped7002     cl1067   2024-07-13   433.46    Cancelado
2   ped7003     cl1097   2025-05-02   352.01    Cancelado
3   ped7004     cl1068   2024-12-20  1182.84      Enviado
4   ped7005     cl1030   2024-04-02  2154.60  Preparacion
5   ped7006     cl1091   2025-03-05  1921.17      Enviado
6   ped7007     cl1086   2024-10-21  1402.07  Preparacion
7   ped7008     cl1002   2024-08-04   404.61  Preparacion
8   ped7009     cl1084   2024-03-30   987.29    Pendiente
9   ped7010     cl1059   2024-06-16  1802.57    Cancelado

In [32]:
#VALIDAR LA CARGA
pd.read_sql(
    "SELECT * FROM pedidos_rejects_parcial02 LIMIT 10",
    engine
)

  id_pedido id_cliente fecha_pedido    monto       estado      motivo_rechazo
0   ped7001       None   2025-01-31  2395.24    Cancelado    id_cliente_vacio
1   ped7018     cl1098          NaT  1031.79    Cancelado  fecha_pedido_vacio
2   ped7023     cl1007          NaT  1780.74  Preparacion  fecha_pedido_vacio
3   ped7025     cl1007   2024-08-22      NaN  Preparacion         monto_vacio
4   ped7056       None   2024-09-16   592.51      Enviado    id_cliente_vacio
5   ped7063     cl1096   2024-03-25      NaN    Entregado         monto_vacio
6   ped7074       None   2024-08-04   723.41    Pendiente    id_cliente_vacio
7   ped7075     cl1132   2024-02-25      NaN    Pendiente         monto_vacio
8   ped7083     cl1002          NaT  2405.04    Entregado  fecha_pedido_vacio
9   ped7100     cl1039   2025-03-21      NaN    Entregado         monto_vacio